CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) NOT NULL UNIQUE,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(320) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    auth_version INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE token_blocklist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jti VARCHAR(100) NOT NULL UNIQUE,
    created_at BIGINT NOT NULL,
    expires_at BIGINT
);

CREATE TABLE verification_codes (
    email VARCHAR(320) PRIMARY KEY,
    code VARCHAR(128) NOT NULL,
    expires_at DOUBLE PRECISION NOT NULL,
    purpose VARCHAR(32) NOT NULL DEFAULT 'register',
    last_sent_at BIGINT NOT NULL DEFAULT 0,
    failed_attempts INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE request_rate_limits (
    key_hash VARCHAR(128) PRIMARY KEY,
    scope VARCHAR(64) NOT NULL,
    window_started_at BIGINT NOT NULL,
    request_count INTEGER NOT NULL
);

CREATE TABLE books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_public_id VARCHAR(36) NOT NULL REFERENCES users(public_id) ON DELETE CASCADE,
    folder VARCHAR(160) NOT NULL,
    job_id VARCHAR(36) UNIQUE,
    status VARCHAR(32) NOT NULL,
    title TEXT,
    author TEXT,
    cover_file TEXT,
    text_file TEXT,
    source_pdf TEXT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    UNIQUE(owner_public_id, folder)
);

CREATE TABLE usage_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_uuid VARCHAR(36) NOT NULL REFERENCES users(public_id) ON DELETE CASCADE,
    event_id VARCHAR(36) NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    book_id VARCHAR(160),
    occurred_at BIGINT NOT NULL,
    duration_seconds INTEGER NOT NULL,
    page_turns INTEGER NOT NULL DEFAULT 0,
    progress_percent INTEGER NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    UNIQUE(user_uuid, event_id)
);

CREATE INDEX idx_rate_limits_window ON request_rate_limits(window_started_at);
CREATE INDEX idx_books_owner_updated ON books(owner_public_id, updated_at DESC);
CREATE INDEX idx_usage_events_user_occurred ON usage_events(user_uuid, occurred_at);
CREATE INDEX idx_usage_events_type_occurred ON usage_events(event_type, occurred_at);
