CREATE TABLE processing_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    request_id VARCHAR(36) NOT NULL,
    queue_job_id VARCHAR(36),
    process_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 3,
    model_version VARCHAR(160),
    started_at BIGINT,
    finished_at BIGINT,
    error_code VARCHAR(64),
    error_message TEXT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT fk_processing_runs_book
        FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE,
    CONSTRAINT uq_processing_runs_request UNIQUE (request_id),
    CONSTRAINT uq_processing_runs_queue_job UNIQUE (queue_job_id),
    CONSTRAINT ck_processing_runs_type
        CHECK (process_type IN ('ANALYZE', 'MUSIC_GENERATION')),
    CONSTRAINT ck_processing_runs_status
        CHECK (status IN ('QUEUED', 'RUNNING', 'CANCEL_REQUESTED',
                          'CANCELLED', 'SUCCEEDED', 'FAILED')),
    CONSTRAINT ck_processing_runs_attempts
        CHECK (attempt_count >= 0 AND max_attempts > 0 AND attempt_count <= max_attempts),
    CONSTRAINT ck_processing_runs_time_order
        CHECK (finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at)
);

CREATE TABLE book_artifacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    processing_run_id BIGINT NOT NULL,
    artifact_type VARCHAR(32) NOT NULL,
    storage_key TEXT NOT NULL,
    file_name TEXT NOT NULL,
    checksum VARCHAR(64),
    file_size BIGINT,
    version INTEGER NOT NULL DEFAULT 1,
    created_at BIGINT NOT NULL,
    CONSTRAINT fk_book_artifacts_processing_run
        FOREIGN KEY (processing_run_id) REFERENCES processing_runs(id) ON DELETE CASCADE,
    CONSTRAINT uq_book_artifacts_run_type_version
        UNIQUE (processing_run_id, artifact_type, version),
    CONSTRAINT ck_book_artifacts_type
        CHECK (artifact_type IN ('SOURCE_PDF', 'BOOK_JSON', 'COVER_IMAGE', 'MUSIC_INDEX')),
    CONSTRAINT ck_book_artifacts_size
        CHECK (file_size IS NULL OR file_size >= 0),
    CONSTRAINT ck_book_artifacts_version
        CHECK (version > 0)
);

CREATE TABLE music_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signature VARCHAR(128) NOT NULL,
    asset_source VARCHAR(32) NOT NULL,
    prompt TEXT NOT NULL,
    genre VARCHAR(64) NOT NULL,
    bpm INTEGER NOT NULL,
    keywords_json TEXT NOT NULL DEFAULT '[]',
    model_name VARCHAR(160) NOT NULL,
    model_version VARCHAR(160) NOT NULL,
    generation_params_json TEXT NOT NULL DEFAULT '{}',
    storage_key TEXT,
    checksum VARCHAR(64),
    duration_seconds INTEGER,
    status VARCHAR(32) NOT NULL,
    reuse_count INTEGER NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    last_used_at BIGINT,
    CONSTRAINT uq_music_assets_signature UNIQUE (signature),
    CONSTRAINT uq_music_assets_storage_key UNIQUE (storage_key),
    CONSTRAINT ck_music_assets_source
        CHECK (asset_source IN ('AI_GENERATED', 'DEFAULT')),
    CONSTRAINT ck_music_assets_status
        CHECK (status IN ('GENERATING', 'READY', 'FAILED')),
    CONSTRAINT ck_music_assets_bpm
        CHECK (bpm BETWEEN 20 AND 300),
    CONSTRAINT ck_music_assets_duration
        CHECK (duration_seconds IS NULL OR duration_seconds > 0),
    CONSTRAINT ck_music_assets_reuse_count
        CHECK (reuse_count >= 0),
    CONSTRAINT ck_music_assets_ready_file
        CHECK (status <> 'READY' OR storage_key IS NOT NULL)
);

CREATE TABLE book_music_bindings (
    book_id BIGINT NOT NULL,
    segment_key VARCHAR(160) NOT NULL,
    music_asset_id BIGINT NOT NULL,
    processing_run_id BIGINT,
    binding_type VARCHAR(32) NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    CONSTRAINT pk_book_music_bindings PRIMARY KEY (book_id, segment_key),
    CONSTRAINT fk_book_music_bindings_book
        FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE,
    CONSTRAINT fk_book_music_bindings_asset
        FOREIGN KEY (music_asset_id) REFERENCES music_assets(id) ON DELETE RESTRICT,
    CONSTRAINT fk_book_music_bindings_processing_run
        FOREIGN KEY (processing_run_id) REFERENCES processing_runs(id) ON DELETE SET NULL,
    CONSTRAINT ck_book_music_bindings_type
        CHECK (binding_type IN ('GENERATED', 'CACHE_REUSED', 'DEFAULT'))
);

CREATE INDEX idx_processing_runs_book_created
    ON processing_runs(book_id, created_at DESC);
CREATE INDEX idx_processing_runs_status_updated
    ON processing_runs(status, updated_at);
CREATE INDEX idx_book_artifacts_run_type
    ON book_artifacts(processing_run_id, artifact_type);
CREATE INDEX idx_book_artifacts_checksum
    ON book_artifacts(checksum);
CREATE INDEX idx_music_assets_status_last_used
    ON music_assets(status, last_used_at);
CREATE INDEX idx_music_assets_model
    ON music_assets(model_name, model_version);
CREATE INDEX idx_book_music_bindings_asset
    ON book_music_bindings(music_asset_id);
CREATE INDEX idx_book_music_bindings_processing_run
    ON book_music_bindings(processing_run_id);
