# Auto-generated
MUSIC_GENRES_200 = {
  "edm": "upbeat electronic dance music with energetic synthesizers and heavy bass drops",
  "techno": "driving techno with repetitive beats and hypnotic synthesizers",
  "house": "uplifting house music with soulful vocals and groovy basslines",
  "trance": "euphoric trance music with soaring melodies and progressive build-ups",
  "dubstep": "heavy dubstep with aggressive wub-wub bass and complex rhythms",
  "drum_bass": "fast drum and bass with breakbeats and deep basslines",
  "ambient": "relaxing ambient atmospheric soundscape with soft pads and textures",
  "synthwave": "retro synthwave music with 80s synthesizers and dreamy atmosphere",
  "chiptune": "8-bit chiptune music with retro video game sounds and melodies",
  "industrial": "dark industrial electronic music with metallic percussion and distorted sounds",
  "deep_house": "smooth deep house with warm bass and atmospheric elements",
  "future_house": "modern future house with sharp synths and energetic drops",
  "tropical_house": "sunny tropical house with relaxed beats and island vibes",
  "electro_house": "powerful electro house with aggressive synths and heavy beats",
  "progressive_house": "building progressive house with evolving melodies",
  "breakbeat": "breakbeat with syncopated rhythms and funky elements",
  "electro": "classic electro with robotic sounds and funk influences",
  "glitch_hop": "glitch hop with stuttering beats and electronic textures",
  "wonky": "wonky electronic with off-kilter rhythms and quirky sounds",
  "chillout": "chillout electronic with relaxed beats and atmospheric pads",
  "idm": "intelligent dance music with complex rhythms and experimental sounds",
  "psytrance": "psytrance with Goa influences and hypnotic patterns",
  "hardstyle": "hardstyle with distorted kicks and reverse bass",
  "hardcore": "hardcore techno with extreme BPM and aggressive sounds",
  "gabber": "gabber with very fast tempo and heavy distortion",
  "acid_house": "acid house with squelching 303 basslines",
  "minimal_techno": "minimal techno with stripped-down repetitive elements",
  "downtempo": "downtempo electronic with slow grooves and atmosphere",
  "big_beat": "big beat with breakbeats and rock influences",
  "trip_hop": "trip hop with slow tempo and moody atmosphere",
  "lofi": "calm lofi hip hop beats with smooth jazz chords and vinyl crackle",
  "hiphop": "boom bap hip hop with sampled drums and jazzy loops",
  "trap": "modern trap music with 808 bass and hi-hat rolls",
  "rnb": "smooth R&B with soulful vocals and warm pads",
  "afrobeats": "energetic afrobeats with polyrhythmic percussion and catchy melodies",
  "reggaeton": "latin reggaeton with dembow rhythm and tropical synths",
  "drill": "dark uk drill with sliding 808s and aggressive hi-hats",
  "jazz_hop": "jazzy hip hop with live instrument samples and complex chords",
  "boombap": "classic boom bap hip hop with sampled breaks and scratches",
  "lo_fi_hiphop": "study focused lo-fi hip hop with relaxed beats and calm atmosphere",
  "old_school_hiphop": "old school hip hop with funk samples and classic beats",
  "east_coast_hiphop": "east coast hip hop with lyrical complexity and jazz samples",
  "west_coast_hiphop": "west coast hip hop with g-funk synths and smooth flows",
  "southern_hiphop": "southern hip hop with heavy bass and drawled vocals",
  "conscious_hiphop": "conscious hip hop with meaningful lyrics and social commentary",
  "jazz_rap": "jazz rap with live instrumentation and complex rhythms",
  "mumble_rap": "mumble rap with melodic flows and auto-tune",
  "gangsta_rap": "gangsta rap with hardcore lyrics and gritty production",
  "chopped_and_screwed": "chopped and screwed with slowed tempo and echoed effects",
  "grime": "grime with fast-paced flows and electronic beats",
  "rock": "powerful rock music with electric guitars, drums and energetic rhythm",
  "metal": "heavy metal with distorted guitars, aggressive drums and powerful riffs",
  "punk": "fast punk rock with raw energy and simple power chords",
  "grunge": "90s grunge with fuzzy guitars and melancholic vocals",
  "hard_rock": "classic hard rock with guitar solos and driving rhythm section",
  "progressive_rock": "progressive rock with complex time signatures and technical playing",
  "alternative_rock": "alternative rock with experimental sounds and emotional vocals",
  "indie_rock": "indie rock with jangly guitars and introspective lyrics",
  "post_rock": "cinematic post-rock with crescendos and atmospheric guitars",
  "metalcore": "modern metalcore with breakdowns and screamed vocals",
  "glam_rock": "glam rock with flamboyant style and anthemic choruses",
  "psychedelic_rock": "psychedelic rock with experimental sounds and trippy effects",
  "folk_rock": "folk rock with acoustic elements and storytelling",
  "southern_rock": "southern rock with blues influences and guitar harmonies",
  "blues_rock": "blues rock with 12-bar blues structure and electric guitar",
  "soft_rock": "soft rock with smooth melodies and gentle production",
  "pop_rock": "pop rock with catchy hooks and radio-friendly sound",
  "arena_rock": "arena rock with anthemic songs and big production",
  "post_punk": "post-punk with angular guitars and atmospheric production",
  "emo": "emo rock with emotional lyrics and dynamic shifts",
  "pop": "catchy pop music with memorable melodies and clean production",
  "k_pop": "k-pop with polished production and synchronized choreography",
  "j_pop": "j-pop with upbeat tempo and cheerful melodies",
  "synth_pop": "synth-pop with electronic synthesizers and pop structures",
  "dream_pop": "dream pop with ethereal vocals and hazy atmosphere",
  "indie_pop": "indie pop with DIY aesthetic and catchy songs",
  "power_pop": "power pop with strong melodies and guitar-driven sound",
  "jazz": "smooth jazz with saxophone, piano and double bass",
  "blues": "traditional blues with 12-bar progression and soulful guitar",
  "soul": "60s soul music with brass section and emotive vocals",
  "funk": "groovy funk with syncopated basslines and tight horns",
  "fusion": "jazz fusion with complex harmonies and rock elements",
  "bebop": "fast bebop jazz with intricate melodies and improvisation",
  "cool_jazz": "cool jazz with relaxed tempo and subdued emotion",
  "modal_jazz": "modal jazz with modal scales and extended improvisation",
  "classical": "beautiful classical orchestral music with strings and piano",
  "baroque": "baroque classical music with harpsichord and counterpoint",
  "romantic": "romantic era classical with emotional melodies and dynamics",
  "impressionist": "impressionist classical music with atmospheric harmonies",
  "renaissance": "renaissance classical with polyphonic textures",
  "modern_classical": "modern classical with contemporary techniques",
  "chamber_music": "chamber music for small ensemble intimacy",
  "opera": "opera with dramatic singing and orchestral accompaniment",
  "choral": "choral music with harmonious singing and religious themes",
  "orchestral": "orchestral music with full symphony orchestra",
  "symphonic": "symphonic music with structured movements",
  "film_score": "film score with cinematic emotion and themes",
  "neoclassical": "neoclassical with modern classical influences",
  "minimalism": "minimalist classical with repetitive patterns",
  "contemporary_classical": "contemporary classical with experimental approaches",
  "acoustic": "gentle acoustic guitar music with warm folk melodies",
  "folk": "traditional folk music with acoustic instruments and storytelling",
  "celtic": "celtic music with fiddle, flute and driving rhythms",
  "flamenco": "passionate flamenco with Spanish guitar and percussive elements",
  "salsa": "lively salsa music with brass section and complex percussion",
  "reggae": "laid-back reggae with off-beat rhythm and positive vibes",
  "samba": "Brazilian samba with fast percussion and carnival energy",
  "bluegrass": "American bluegrass with banjo, fiddle and vocal harmonies",
  "country": "country music with twangy guitars and storytelling lyrics",
  "gospel": "uplifting gospel music with choir and piano",
  "bossa_nova": "bossa nova with smooth rhythms and Portuguese vocals",
  "tango": "dramatic tango with bandoneon and passionate dance rhythm",
  "soca": "soca with Caribbean rhythms and festive energy",
  "calypso": "calypso with Caribbean storytelling and steel drums",
  "merengue": "merengue with fast tempo and Dominican rhythm",
  "bachata": "bachata with romantic lyrics and guitar rhythms",
  "cumbia": "cumbia with Colombian rhythm and accordion",
  "mariachi": "mariachi with trumpets and Mexican tradition",
  "klezmer": "klezmer with Eastern European Jewish melodies",
  "fado": "fado with Portuguese melancholy and guitar",
  "cinematic": "epic cinematic music for films, with orchestral swells",
  "video_game": "adventure video game music with memorable melodies",
  "fantasy": "fantasy RPG music with magical atmosphere and adventure",
  "horror": "suspenseful horror music with dissonant strings and tension",
  "sci_fi": "futuristic sci-fi music with electronic and orchestral blend",
  "western": "spaghetti western music with whistling and acoustic guitar",
  "noir": "film noir music with jazz influences and mysterious vibe",
  "anime": "Japanese anime soundtrack with emotional strings and piano",
  "battle": "epic battle music with driving percussion and brass",
  "medieval": "medieval tavern music with lute, flute and drums",
  "epic": "epic orchestral music with choir and powerful themes",
  "adventure": "adventure music with sense of exploration and wonder",
  "mystery": "mystery music with suspense and unanswered questions",
  "romantic_film": "romantic film music with emotional strings and piano",
  "documentary": "documentary music with informative and neutral tone",
  "trailer": "movie trailer music with building tension and impact",
  "superhero": "superhero theme music with heroic brass and power",
  "space": "space music with atmospheric pads and sense of vastness",
  "underwater": "underwater music with fluid textures and deep atmosphere",
  "dream": "dream sequence music with surreal and ethereal sounds",
  "experimental": "experimental electronic music with unconventional sounds",
  "noise": "abstract noise music with textured layers and distortion",
  "minimal": "minimalist music with repetitive patterns and gradual changes",
  "drone": "drone music with sustained tones and slowly evolving textures",
  "glitch": "glitch music with digital artifacts and stuttering beats",
  "vaporwave": "vaporwave with slowed down samples and nostalgic vibe",
  "future_bass": "future bass with pitched vocal chops and supersaws",
  "city_pop": "Japanese city pop with funky bass and smooth vocals",
  "dark_ambient": "dark ambient with oppressive atmosphere and drones",
  "space_music": "space music with cosmic sounds and atmosphere",
  "isolationism": "isolationist ambient with lonely and desolate sounds",
  "lowercase": "lowercase music with extremely quiet and minimal sounds",
  "microsound": "microsound with microscopic audio details and textures",
  "soundscape": "soundscape with environmental recordings and atmosphere",
  "field_recording": "field recording with natural environmental sounds",
  "new_age": "new age music with spiritual and healing qualities",
  "easy_listening": "easy listening with pleasant and unobtrusive melodies",
  "lounge": "lounge music with sophisticated and relaxed atmosphere",
  "exotica": "exotica with tropical and mysterious sounds",
  "yodeling": "yodeling with rapid pitch changes and Alpine style",
  "sea_shanty": "sea shanty with nautical themes and group singing",
  "marching_band": "marching band music with brass and percussion",
  "polka": "polka with lively dance rhythm and accordion",
  "brass_band": "brass band music with ensemble brass instruments",
  "military_music": "military music with marches and patriotic themes",
  "disco": "disco with four-on-the-floor beat and funky bass",
  "eurodance": "eurodance with synthesizers and dance-pop structure",
  "italo_disco": "italo disco with European disco and synth sounds",
  "handbag_house": "handbag house with piano riffs and vocal samples",
  "nu_disco": "nu disco with modern disco revival and funk influences",
  "electroclash": "electroclash with punk attitude and electronic sounds",
  "dancehall": "dancehall with Jamaican rhythm and toasting",
  "hardbag": "hardbag with hard house and baggy influences",
  "country_blues": "country blues with acoustic blues and folk elements",
  "delta_blues": "delta blues with slide guitar and raw emotion",
  "chicago_blues": "Chicago blues with electric blues and urban sound",
  "texas_blues": "Texas blues with swing influences and guitar",
  "swamp_blues": "swamp blues with Louisiana influence and laid-back rhythm",
  "honky_tonk": "honky tonk with piano and classic country sound",
  "outlaw_country": "outlaw country with rebellious themes and raw sound",
  "americana": "americana with American roots music blend",
  "alt_country": "alt country with alternative rock and country blend",
  "country_pop": "country pop with pop melodies and country instrumentation"
}
